almost completely implemented plterm-ui. im probably gonna release this as is anyway, this update sucks >~<

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,8 +1,11 @@
 #!/bin/sh
 set -e
+parser_skip=0
 start_time=""
 end_time=""
-action="compile_lib"
+action=""
+lib_projectstruct=""
+exec_projectstruct=""
 
 _compile_obj(){
 	extra_flag=""
@@ -22,10 +25,26 @@ _compile_obj(){
 }
 
 _parse_projectstruct(){
-	libname=$(echo "$1" | cut -d'|' -f1)
-	src=$(echo "$1" | cut -d'|' -f2 | sed 's/,/\ /g')
-	libtest=$(echo "$1" | cut -d'|' -f3)
-	srcdir=$(echo "$1" | cut -d'|' -f4)
+	project_type=$(echo $1 | cut -d'|' -f1)
+
+	if [ "$project_type" = "lib" ]; then
+		libname=$(echo "$1" | cut -d'|' -f2)
+		libsrc=$(echo "$1" | cut -d'|' -f3 | sed 's/,/\ /g')
+		srcdir=$(echo "$1" | cut -d'|' -f4)
+	elif [ "$project_type" = "exec" ]; then
+		progname=$(echo "$1" | cut -d'|' -f2)
+		srcdir=$(echo "$1" | cut -d'|' -f3)
+		linkflags=$(echo "$1" | cut -d'|' -f4 | sed 's/,/\ /g')
+		prog_no_install=$(echo "$1" | cut -d'|' -f5)
+	fi
+
+	if [ "$linkflags" = "''" ]; then
+		linkflags=""
+	fi
+
+	if [ "$srcdir" = "" ]; then
+		srcdir="src"
+	fi
 }
 
 _runtime_calc(){
@@ -65,70 +84,142 @@ _runtime_calc(){
 }
 
 compile_static_lib(){
-	if [ "$srcdir" = "" ]; then
-		srcdir="src"
-	fi
 	mkdir obj -p
 
-	for i in $src; do
+	for i in $libsrc; do
 		_compile_obj $srcdir/$i.c "static"
 	done
-	printf "Creating static library $1..."
+	printf "Creating static library $libname..."
 	$AR rc lib$libname.a $(find obj | grep static) 2>&1 >/dev/null
 	echo "Done."
 }
 
 compile_shared_lib(){
-	if [ "$srcdir" = "" ]; then
-		srcdir="src"
-	fi
 	mkdir obj -p
 
-	for i in $src; do
+	for i in $libsrc; do
 		_compile_obj $srcdir/$i.c "shared"
 	done
-	printf "Creating shared library $1..."
+	printf "Creating shared library $libname..."
 	$CC -shared $(find obj | grep shared) -o lib$libname.so $CFLAGS $LDFLAGS
 	echo "Done."
 	rm *.o -f
 }
 
-compile_test(){
-	printf "Compiling test program $libtest..."
-	$CC $libtest.c -Iinclude -L. -l$libname -static $CFLAGS $LDFLAGS -o $libtest.out
+compile_prog(){
+	printf "Compiling program $srcdir/$progname..."
+	$CC $srcdir/$progname.c -Iinclude -L. $linkflags $CFLAGS -o $progname
 	echo "Done."
-}
-
-compile_lib(){
-	compile_static_lib
-	compile_shared_lib
 }
 
 install_lib(){
 	printf "Installing library $libname..."
 	for i in $(ls include | grep ".h"); do
-		cp include/$i "$prefix/include"
+		cp include/$i "$includedir"
 	done
-	mv lib$libname.* "$prefix/lib"
+	mv lib$libname.* "$libdir"
 	echo "Done."
 }
 
-printf "PocketLinux32's Generic C Library Build System v0.07\n\n"
+install_prog(){
+	if [ "$prog_no_install" != "" ]; then
+		echo "Skipping $progname"
+		return
+	fi
+
+	printf "Installing program $progname..."
+	mv $progname "$bindir"
+	echo "Done."
+}
+
+clean_lib(){
+	printf "Cleaning library $libname..."
+	rm -f lib$libname.*
+	echo "Done."
+}
+
+clean_prog(){
+	printf "Cleaning program $progname..."
+	rm -f $progname
+	echo "Done."
+}
+
+build_project(){
+	if [ "$1" = "" ]; then
+		internal_action="lib"
+	else
+		internal_action="$1"
+	fi
+
+	if [ $internal_action = "lib" ]; then
+		if [ "$2" = "" ]; then
+			internal_lib_action="shared-static"
+		else
+			internal_lib_action="$2"
+		fi
+
+		if [ $(echo $internal_lib_action | grep "static" -c) -ne 0 ]; then
+			compile_static_lib
+		fi
+
+		if [ $(echo $internal_lib_action | grep "shared" -c) -ne 0 ]; then
+			compile_shared_lib
+		fi
+	fi
+
+	if [ $internal_action = "prog" ]; then
+		compile_prog
+	fi
+}
+
+install_project(){
+	if [ "$1" = "" ]; then
+		internal_action="lib"
+	else
+		internal_action="$1"
+	fi
+
+	if [ $internal_action = "lib" ]; then
+		install_lib
+	fi
+
+	if [ $internal_action = "prog" ]; then
+		install_prog
+	fi
+}
+
+clean_project(){
+	if [ "$1" = "" ]; then
+		internal_action="lib"
+	else
+		internal_action="$1"
+	fi
+
+	if [ $internal_action = "lib" ]; then
+		clean_lib
+	fi
+
+	if [ $internal_action = "prog" ]; then
+		clean_prog
+	fi
+}
+
+printf "PocketLinux32's Generic C Build System v0.03\n\n"
+
+if [ $# -lt 1 ]; then
+	echo "Error: Not enough arguments. Please run $0 help to see all of the valid options and try again"
+	exit 1
+fi
 
 case $1 in
 	clean)
-		rm obj *.out *.a *.so core* -rf
-		if [ "$2" = "fully" ]; then
-			rm .config
-		fi
-		echo "Project directory has been cleaned"
-		exit 0
+		action="clean_project"
 		;;
 	build)
-		action="compile_$2"
+		action="build_project"
 		;;
 	install)
-		action="install_lib"
+		action="install_project"
 		;;
 	help)
 		echo "clean			Removes any files generated during compilation"
@@ -136,6 +227,9 @@ case $1 in
 		echo "install		Installs the compiled library to dest"
 		exit 0
 		;;
+	*)
+		echo "Error: Unrecognized option. Please run $0 help to see all of the valid options and try again"
+		exit 1
 esac
 
 if [ ! -f ".config" ]; then
@@ -149,7 +243,39 @@ echo "Compiler Flags: $CFLAGS"
 printf "Linker Flags: $LDFLAGS\n\n"
 
 _runtime_calc start
-_parse_projectstruct $main_project
-$action
-_runtime_calc stop
+for i in $main_project; do
+	project_type=$(echo $i | cut -d'|' -f1)
 
+	if [ "$project_type" = "lib" ]; then
+		if [ "$lib_projectstruct" = "" ]; then
+			lib_projectstruct="$i"
+		else
+			lib_projectstruct="$lib_projectstruct $i"
+		fi
+	elif [ "$project_type" = "exec" ]; then
+		if [ "$exec_projectstruct" = "" ]; then
+			exec_projectstruct="$i"
+		else
+			exec_projectstruct="$exec_projectstruct $i"
+		fi
+	fi
+done
+
+if [ "$action" = "clean_project" ]; then
+	rm -rf obj core*
+	if [ "$2" = "fully" ]; then
+		rm -f .config
+	fi
+fi
+
+for i in $lib_projectstruct; do
+	_parse_projectstruct $i
+	$action lib $3
+done
+
+for i in $exec_projectstruct; do
+	_parse_projectstruct $i
+	$action prog
+done
+
+_runtime_calc stop
